version: 2.1
jobs:
  my-java:
    docker:
      - image: cimg/openjdk:17.0.0
    steps:
      - checkout
      - run: cd hello-java/app-src/
      - run: mvn clean install
workflows:
  JAVA-workflow:
    jobs:
      - my-java